displayName: Test_News_Fetching
schemaName: cr921_TestNewsFetching
accessControlPolicy: GroupMembership
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  channels:
    - channelId: MsTeams

    - channelId: Microsoft365Copilot

  settings:
    GenerativeActionsEnabled: false

  isAgentConnectable: false
  publishOnImport: true
  gPTSettings:
    defaultSchemaName: cr921_TestNewsFetching.gpt.default

  isLightweightBot: false
  aISettings:
    useModelKnowledge: true
    isFileAnalysisEnabled: false
    isSemanticSearchEnabled: true
    contentModeration: Low
    optInUseLatestModels: false

  deferredProvisioning: false

publishedOn: 2026-08-13T09:39:07.0000000Z
template: default-2.1.0
language: 1033